openapi: 3.0.3
info:
  title: My API
  description: An example OpenAPI 3.0 specification
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: Development server

paths:
  /api/v1/users/_register:
    post:
      summary: Register
      description: Register a new user
      requestBody:
        description: Example data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                nim:
                    type: string
                    format: email
                name:
                    type: string
                password:
                    type: string
                    format: password
                confirm_password:
                  type: string
                  format: password
              required:
                - email
                - nim
                - name
                - password
                - confirm_password
      responses:
        '201':
          description: User created

          content:
            application/json:
              schema:

                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                  status:
                    type: string
                  data:


                    type: object
                    properties:
                      ref_code:
                        type: string
                      user_register:
                        type: object
                        properties:
                          id:
                            type: integer
                            format: int32
                          email:
                            type: string
                            format: email
                          nim:
                            type: string
                            format: email
                          name:
                            type: string
                          password:
                            type: string
                            format: password
                          confirm_password:
                            type: string
                            format: password

        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                  status:
                    type: string
                  data:
                    type: null




