version: "3.9"
services:


  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=amikom_pedia

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    environment:
      - PORT_APP=8080
      - DB_DSN=postgres://root:root@localhost:5432/amikompedia?sslmode=disable
      - APP_NAME=AmikomPedia
      - GO_ENV=DEV
      - TOKEN_SYMETRIC_KEY=msfwvvokev71979lkfoqjipld97802jw
      - TOKEN_ACCESS_DURATION=60m
      - EMAIL_NAME=Amikom Pedia
      - EMAIL_SENDER=amikompedia@gmail.com
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
